### ISSUE TITLE
Add option to pass HTTP headers

### ISSUE THREAD

**Issue by onlyflix** [graphql-editor/graphql-zeus#10]
Our GraphQL API is protected by a HTTP Authorization header. 
The option to pass this header when fetching the Schema from an URL would be nice.

**Comment by aexol** [comment]
Ok doing that in CLI then. However, in the generated code it is possible to use headers right now :
```ts
Api(projectApiURL, {
      method: "GET",
      mode: "cors",
      headers: new Headers({
        Authorization: `Bearer ${token}`
      })
    });
```

like this

**Comment by aexol** [comment]
Done and released ! @onlyflix  thanks
