### ISSUE TITLE
How to use ZeusSelect selection set in generic componet?

### ISSUE THREAD

**Issue by martinsura** [graphql-editor/graphql-zeus#112]
Hello,

First nice idea and library.

I am trying implement ZeusSelect selection set in generic react component.

Code:

```
import * as React from "react";
import { render } from "react-dom";
import { ZeusSelect, Card } from "./zeus-graphql";

type Props<T> = {
  selector: T;
  onSelect: (item: T) => void;
};

const GenericComponent = <T extends {}>(props: Props<T>) => {
  return <p>Helo world</p>;
};

export default function App() {
  const cardSelector2 = ZeusSelect<Card>()({
    name: true,
    description: true,
    Attack: true,
    skills: true,
    Defense: true,
    cardImage: {
      key: true,
      bucket: true
    }
  });

  return (
    <GenericComponent
      selector={cardSelector2}
      onSelect={item => alert(item.name)}
    />
  );
}
```
This code works well except one problem: item.name in onSelect event is type boolean instead of string.

Is here any workaround ? Maybe define onSelect as ```onSelect:(item: RealObject<T>) => void;``` ?

Thanks

**Comment by aexol** [comment]
Hi, your T extends {} so it is already an object. Also I don't understand what you want to do. Maybe use PlainObjects togerher with ValueTypes so you define T as a keyof both PlainObjects and ValueTypes from Zeus

**Comment by martinsura** [comment]
Np found anotherway how to define component. Thanks
