### ISSUE TITLE
Typescript code in javascript generated file

### ISSUE THREAD

**Issue by js2me** [graphql-editor/graphql-zeus#119]
Generate output js file from schema from [graphql-zeus examples](https://github.com/graphql-editor/graphql-zeus/blob/master/examples/typescript-node/zeus.graphql)
I use this command to generate output:
```
zeus ./schemas/schema.gql ./generated  --node
```
Thats output file which contains `: Record<string, any>` which is not JavaScript syntax
![image](https://user-images.githubusercontent.com/16340911/70675100-40be2a80-1c99-11ea-8888-89f96f2e6c9e.png)

**Comment by aexol** [comment]
Thanks for spotting the bug! @js2me
