### ISSUE TITLE
Consider not omitting Zeus.Mutation

### ISSUE THREAD

**Issue by adam-stanek** [graphql-editor/graphql-zeus#123]
The library is clever to not include `Zeus.Mutation` in generated types if server doesn't have any mutations defined. This might seem like a nice optimization but it might in fact break libraries which are endpoint agnostic.

For example I am writing client API wrapper for my tests which exposes `query` and `mutate` functions (they use `Zeus.Query` and `Zeus.Mutation` under the hood). I cannot use the same implementation in simple project which has only queries defined (the Typescript will complain because of unresolveable `Zeus.Mutation` type). With the current implementation I would have to remove the `mutate` function which doesn't really make sense since it is supposed to be reusable package.

**Comment by aexol** [comment]
Can you contribute this solution?

**Comment by adam-stanek** [comment]
Sorry, not at the moment. It is not a critical issue, but it is something it might be good to keep in mind in future development to avoid this sort of problems.
