### ISSUE TITLE
Nested fields types are not recognized (typescript)

### ISSUE THREAD

**Issue by alekbarszczewski** [graphql-editor/graphql-zeus#124]
<img width="750" alt="zeus_ts_—_eqx-cms" src="https://user-images.githubusercontent.com/2742373/72063545-429bfd80-32da-11ea-9d0b-3a23579292d1.png">

<img width="530" alt="zeus_ts_—_eqx-cms" src="https://user-images.githubusercontent.com/2742373/72063737-a7575800-32da-11ea-9d1b-9fa1187ca90f.png">

Any idea why it does not autocomplete/typecheck nested fields?

"graphql-zeus": "^2.4.7"
generated with `zeus http://localhost:5000/graphql ./src/generated --ts`

**Comment by aexol** [comment]
This is how inferred types work in TypeScript right now you break the type you lose autocomplete. Can you PM me the schema or zeus file so I can tell you more?

**Comment by alekbarszczewski** [comment]
Ok, got it.
Autocomplete seems to work for fields, but not for variables.

<img width="586" alt="Menubar_and_zeus_ts_—_eqx-cms" src="https://user-images.githubusercontent.com/2742373/72064865-23529f80-32dd-11ea-8531-6c961b4d71aa.png">

* When I type field selector it autocompletes and guesses type of field in query result.
* When I type invalid field selector it does not complain, however in query result type invalid field is marked as `unknown`

^ Is this how it should work?

<img width="561" alt="zeus_ts_—_eqx-cms" src="https://user-images.githubusercontent.com/2742373/72064955-57c65b80-32dd-11ea-833c-7d2b4f99ab4b.png">

<img width="938" alt="Banners_and_Alerts_and_zeus_ts_—_eqx-cms" src="https://user-images.githubusercontent.com/2742373/72065196-fd79ca80-32dd-11ea-9140-4775edeae877.png">

**Comment by aexol** [comment]
Autocomplete works for input fields also
![Screen Shot 2020-01-09 at 16 04 05](https://user-images.githubusercontent.com/779748/72078617-b994be80-32f9-11ea-8758-73ec1304e07e.png)

**Comment by aexol** [comment]
With mapping non existing type to object type that doesnt have the field the type should be unknown
