### ISSUE TITLE
Root queries with names other than Query produce error:  "Cannot read property 'getQueryType' of undefined"

### ISSUE THREAD

**Issue by OkkioXavier** [graphql-editor/graphql-zeus#125]
When running the following command:

npx zeus http://localhost:5000/api/graphql ./src/generated/graphql --ts

The following exception was thrown:

> (node:16840) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getQueryType' of undefined
>     at Function.Parser.parse (D:\ClientApp\node_modules\graphql-zeus\lib\Parser\index.js:56:26)
>     at Function.Parser.parseAddExtensions (D:\ClientApp\node_modules\graphql-zeus\lib\Parser\index.js:93:27)
>     at Function.TranslateGraphQL.typescript (D:\ClientApp\node_modules\graphql-zeus\lib\TranslateGraphQL\index.js:9:34)
>     at D:\ClientApp\node_modules\graphql-zeus\lib\CLI\CLIClass.js:41:74
>     at Generator.next (<anonymous>)
>     at fulfilled (D:\ClientApp\node_modules\graphql-zeus\lib\CLI\CLIClass.js:5:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:16840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:16840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I compared the schema at: https://faker.graphqleditor.com/aexol/olympus/graphql and my own 'empty' schema and found that renaming my root query to Query resolved the issue.

**Comment by aexol** [comment]
Please send me the schema so I can reproduce the error

**Comment by OkkioXavier** [comment]
[not.working.introspection.txt](https://github.com/graphql-editor/graphql-zeus/files/4064927/not.working.introspection.txt)
[working.introspection.txt](https://github.com/graphql-editor/graphql-zeus/files/4064928/working.introspection.txt)
[not.working.schema.graphql.txt](https://github.com/graphql-editor/graphql-zeus/files/4064930/not.working.schema.graphql.txt)
[working.schema.graphql.txt](https://github.com/graphql-editor/graphql-zeus/files/4064933/working.schema.graphql.txt)

**Comment by aexol** [comment]
Your errors:
- not working schema has Foo query wchich is not declared
- not working schema has type Query without fields
I am workin hard on releasing new IDE to graphql editor this week. It would find this error for you

**Comment by OkkioXavier** [comment]
@aexol Sorry about the errors in my minimal examples. 

The schema which caused the initial error wasn't written by hand though. It's generated by graphql-dotnet and I'm pulling it directly from a server using zeus.

I hadn't noticed that zeus outputs the schema on failure when running the command `npx zeus http://localhost:5000/api/graphql ./src/generated/graphql --ts --graphql ./src/generated/graphql`. I've included all the output below:

[console.txt](https://github.com/graphql-editor/graphql-zeus/files/4065240/console.txt)

The schema output by the command seems to include two instances of the following:

```
schema {
  query: Foo
}
```

If this is another non-issue I'll stop bothering you I just thought it might be relevant.

**Comment by aexol** [comment]
It is indeed a problem with your schema server. Try running zeus with other graphql servers. There is no problem with that. You can also fork the repo and test included examples
