### ISSUE TITLE
Support glob patterns for local schema files

### ISSUE THREAD

**Issue by tkamenoko** [graphql-editor/graphql-zeus#130]
Currently `graphql-zeus` can load only single schema file, but a large schema file is often split into multiple files in development. So I think that supporting glob patterns is reasonable and improves usability.

usage example:
```shell
$ zeus ./schema/**/*.graphql ./  
```

**Comment by aexol** [comment]
Hi,

Do you mean to generate one autocomplete library out of all files or multiple libraries from multiple files?

**Comment by tkamenoko** [comment]
@aexol  one autocomplete library from `*.graphql` files.

**Comment by aexol** [comment]
Ok I understand right now. It is out of scope of my work for this package, but I am not closing it since maybe somebody will take it.
