### ISSUE TITLE
Is it possible to simplify the return type of Chain.query?

### ISSUE THREAD

**Issue by OkkioXavier** [graphql-editor/graphql-zeus#131]
Currently the generated return type of Chain.query is:

`type OperationToGraphQL<V, T> = <Z>(o: Z | V) => Promise<MapType<T, Z>>;`

could it be simplified to: 

`type OperationToGraphQL<V, T> = <Z>(o: Z | V) => Promise<T> `

where T is `Partial<Query>`?

This leads to nice friendly return types of:

`const result: Partial<Query> = await Gql.query(query);`

rather than:

`const result: MapType<Query, { bar: ({} | { name: boolean })[] }> = await Gql.query(query);`

which is a bit scary.

The advantage of MapType seems to be that it reflects the original query but it allows invalid access?

Are there other ways to improve upon the current return type?

**Comment by aexol** [comment]
This is not friendly. Mapped types are used so you can know what is returned from particular query. This is all this library is about

**Comment by OkkioXavier** [comment]
Yep, you are right on the above. When I opened this issue I was getting the query definition process wrong:

`        const query: ValueTypes["LearnerContentQuery"] = {
            lessons: [
                {},
                {
                    name: true
                }
            ]
        };`

Setting the type of query to ValueTypes["LearnerContentQuery"] to get completion resulted in very weird return types for Chain.query.

What I should've been doing to get completion was:

`
 let lessonPayload = ZeusSelect<ValueTypes['LessonGraph']>()({
                name: true
        });

        const result = await Gql.query({
            lessons: [
                {name: 'Lesson 1'},
                lessonPayload
            ]
        });
`

This file was also quite helpful for working out how to use it:
[examples/typescript-node-big-schema/src/index.ts](
https://github.com/graphql-editor/graphql-zeus/blob/master/examples/typescript-node-big-schema/src/index.ts)

Doing it the right way gives really really nice code completion for the result of Chain.query.

You're right, map types ARE definitely much more friendly.
