### ISSUE TITLE
Returns React hook (useQuery, useMutation) from queries / mutations

### ISSUE THREAD

**Issue by jgoux** [graphql-editor/graphql-zeus#133]
Hi,

Beautiful library right here! ⭐️ 

I love the approach of constructing your queries or mutations in a type-safe manner, by having a single codegen step for generating the initial client.

I'm coming from graphql-codegen, which scans files for queries written in SDL (so unsafe because they're just string) and then generates typed react hooks to use in our components.

What I'd like is the best of both, so using your approach to generate a single client to write my typed queries and return typed react hooks from them. I assume as the query is typed, there is no need for extra codegen step for generating the hook.

Is this approach even possible to implement?

**Comment by aexol** [comment]
Hi,

It is possible to add option to the cli for example `--react` and then generate code together with react hooks. 

So yes it is possible and I think we all benefit from this change. Thank you!

**Comment by jgoux** [comment]
Just to be sure we're on the same page, this would be code to return hooks from typed queries, not "pregenerated" hooks like graphql-code-generator right?

**Comment by jgoux** [comment]
Thinking about this further, I'm not sure if it's a good idea to add hooks to graphql-zeus.
I played a bit with react-query, and it seems to work great with your library!
The only missing part is https://github.com/graphql-editor/graphql-zeus/issues/48 😄

**Comment by aexol** [comment]
Have you seen unstated-next? Maybe we can create container to hold data from all the queries so all the containers are singleton with one provider. What do you think?

**Comment by jgoux** [comment]
[react-query](https://github.com/tannerlinsley/react-query) does the hard part about caching, refetching so I don't think we need any other lib for this.

The integration is easy and fully typed : 
![image](https://user-images.githubusercontent.com/1443499/74729654-12367000-5245-11ea-8228-08acfc2b0b26.png)

Ideally a tiny wrapper around react-query would be enough, something like this : https://github.com/tannerlinsley/react-query/issues/55

Is there any way to write the typed query but pass it to the client later? So we can introspect the query and get its name for example (so we don't have to manually define a cache key)

**Comment by aexol** [comment]
@jgoux Great library! You have selectors system inside Zeus so you can prepare your selectors and then pass them to query function
```tsx

export const BorderOrderSelector = ZeusSelect<BorderOrder>()({
  colorDisplay: true,
  colorIdentifier: true,
  display: true,
  identifier: true,
});

export const MirrorItemSelector = ZeusSelect<MirrorOrder>()({
  border: BorderOrderSelector,
  height: true,
  id: true,
  quantity: true,
  width: true,
  price: true,
});

export const AddressSelector = ZeusSelect<Address>()({
  city: true,
  firstName: true,
  flat: true,
  lastName: true,
  number: true,
  postalCode: true,
  street: true,
});

export const OrderSelector = ZeusSelect<Order>()({
  address: AddressSelector,
  items: MirrorItemSelector,
  delivery: true,
  payment: true,
  details: true,
  id: true,
  status: true,
});
```

**Comment by aexol** [comment]
@jgoux I've implemented vars - can you provide example of a hook?

**Comment by remorses** [comment]
This library has a very general use case, we should not add additional complexity and not bind it to react.
