### ISSUE TITLE
add support for variables

### ISSUE THREAD

**Issue by regevbr** [graphql-editor/graphql-zeus#135]
Currently, when building dynamic queries, you need to compile the query every time, which is "cpu consuming".
If we can leverage gql variables, and cache our compiled queries, this can provide great improvement in performance.

For example:
```typescript
const runQuery = (x: number) => {
  return chain.query({
    a: {
      b: {
        c: x,
      },
    },
  });
};
``` 

Can be better used like
```typescript
const query = Zeus.query({
  a: {
    b: {
      c: '$x',
    },
  },
});


const runQuery = (x: number) => {
  return chain.query(query, { $x: 1 });
};
```

Of-course this has to be type safe (which my example is not as the return value will not be known)

What do you think?

**Comment by aexol** [comment]
Variables are used for user input to GraphQL queries so type-safe is not a problem here as it stays as is. The type safety should be done by user when declaring the variable

**Comment by aexol** [comment]
```js

  const test = await Zeus.mutation(
    {
      addCard: [
        {
          card: $`card`,
        },
        {
          id: true,
          description: true,
          name: true,
          Attack: true,
          skills: true,
          Children: true,
          Defense: true,
          cardImage: {
            bucket: true,
            region: true,
            key: true,
          },
        },
      ],
    },
    {
      card: {
        Attack: 2,
        Defense: 3,
        description: 'Lord of the mountains',
        name: 'Golrog',
      },
    },
  );
```

**Comment by aexol** [comment]
Above preview of the new syntax. Is it ok?

**Comment by regevbr** [comment]
yes looks perfect!

**Comment by aexol** [comment]
done in `2.6.2`

**Comment by regevbr** [comment]
@aexol I don't see an option to make sure that the queries will be type safe... can you please provide an example? And what about the mapped types? will they accept a string now?

**Comment by aexol** [comment]
@regevbr You don't map input types just return types so making vars doesnt change anything
