### ISSUE TITLE
Wrapping Apollo queries with Zeus typings

### ISSUE THREAD

**Issue by stewartmcgown** [graphql-editor/graphql-zeus#139]
**Issue**
My current attempt to wrap an Apollo query with Zeus typings looks like this:

```ts
export const useTypedQuery = <Data, Variables>(
  query: { [K in keyof ValueTypes["Query"]]: [Variables, Data] },
  options?: QueryHookOptions<Data, Variables>
) => {
  return useQuery<Data, Variables>(
    gql`
      ${Zeus.query(query)}
    `,
    options
  );
};
```

This is... close, but not exactly perfect. It works for variables, but the Data object consists just of all the fields lumped together, as opposed to seperated by query name.

<img width="739" alt="Screen Shot 2020-03-25 at 19 43 33" src="https://user-images.githubusercontent.com/1136276/77578723-f58af900-6ed0-11ea-918b-c7c8001ffea8.png">

I am, of course, missing something to do with getting the conditional types extracted properly. Has anyone managed to do something similar, or know of what I'm missing to actually make this happen?

**Reason**
I've got a large codebase already using Apollo.

**Comment by aexol** [comment]
I'll look into it next week. Meanwhile you can look into `OperationToGraphQL` type

**Comment by stewartmcgown** [comment]
`OperationToGraphQL` and `MapType` look very promising for this. I'm still not getting it to match the results I'd get from `Zeus` or `Gql`, so I'll wait until you've looked into it. Thanks!

**Comment by zhigang1992** [comment]
![image](https://user-images.githubusercontent.com/1057756/82149403-5ad3e880-9889-11ea-887b-57152c482349.png)
I was able to get this to work, but I had to export MapType from the generated file.

**Comment by zhigang1992** [comment]
Here is the complete code
```
import {
  ApolloProvider,
  gql,
  MutationHookOptions,
  QueryHookOptions,
  SubscriptionHookOptions,
  useMutation,
  useQuery,
  useSubscription,
} from "@apollo/client";
import {$, MapType, mutation_root, order_by, query_root, subscription_root, ValueTypes, Zeus,} from "./graphql-zeus";

function useTypedQuery<Q extends ValueTypes["query_root"]>(
  query: Q,
  options?: QueryHookOptions<MapType<query_root, Q>, Record<string, any>>
) {
  return useQuery<MapType<query_root, Q>>(gql(Zeus.query(query)), options);
}

function useTypedMutation<Q extends ValueTypes["mutation_root"]>(
  mutation: Q,
  options?: MutationHookOptions<MapType<mutation_root, Q>, Record<string, any>>
) {
  return useMutation<MapType<mutation_root, Q>>(
    gql(Zeus.mutation(mutation)),
    options
  );
}

function useTypedSubscription<Q extends ValueTypes["subscription_root"]>(
  subscription: Q,
  options?: SubscriptionHookOptions<
    MapType<subscription_root, Q>,
    Record<string, any>
  >
) {
  return useSubscription<MapType<subscription_root, Q>>(
    gql(Zeus.subscription(subscription)),
    options
  );
}
```

**Comment by stewartmcgown** [comment]
Closing as the above comment has a wonderful solution and we now have access to the exported MapType!
