### ISSUE TITLE
Remove undefined fields from query arguments

### ISSUE THREAD

**Issue by remorses** [graphql-editor/graphql-zeus#141]
When i make a query with arguments fields that are `undefined` they are converted to the string `undefined` by the `ScalarResolver` function, it would be better to omit them from the query arguments, like other libraries usually do

```
typedClient.query({
        Type: [
            {
                before: undefined, // is inserted in the query as the string "undefined"
                ...(before ? { before } : {}), // workaround to omit fields, not very readable
           }, 
           {...}
     ]
})
```

**Comment by remorses** [comment]
I forgot to mention that right now the `ScalarResolver` function throws in case of undeifned values because of this 

```
export const ScalarResolver = (scalar: string, value: any) => {
    switch (scalar) {
        case 'String':
            return `"${value?.replace(/"/g, '\\"')}"`
```

it throws with "You cannot call `replace` on undefined" but #113 should fix this

**Comment by aexol** [comment]
I can do that next week
