### ISSUE TITLE
Subscription error

### ISSUE THREAD

**Issue by dquisi** [graphql-editor/graphql-zeus#145]
Hi @aexol
Still appreciating your great work on this lib.
I have a new questions.

How to consume, example or use a type subscription method ?, because I have the next error.

{ errors:
   [ { extensions: [Object],
       message:
        'subscriptions are not supported over HTTP, use websockets instead' } ] }

Thanks

**Comment by mash-graz** [comment]
yes -- this software is really fantastic, but i also stumbled over this lack of feature.

maybe it's possible to workaround this limitation by utilizing apollos [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws), but a small remark in the documentation concerning this topic and possible solutions, would be very helpful, too.

**Comment by remorses** [comment]
This library currently does not support subscriptions, even if the generated types has a `subscription` field
Support for subscription tracked in #148
