### ISSUE TITLE
Multi line string argument

### ISSUE THREAD

**Issue by remorses** [graphql-editor/graphql-zeus#147]
If you try to generate a query with a multi line string argument the generated query is invalid.

For example the following generated query is invalid, the graphql package will throw `Syntax Error: Unterminated string`
```js
await Gql.mutation({
  mutate: [{string: "hello\nbye"}, {something: true}]
})
```
```gql
mutation{mutate(string:"hello
bye") { something }
```

The problem is that \n chars need one more escape, as we already do here for " https://github.com/graphql-editor/graphql-zeus/blob/79520373de44da01798ea23e6a20c098ce1f745d/src/TreeToTS/templates/javascript/functions.ts#L7

The soulution is to replace all escape sequences with double escape sequences

**Comment by remorses** [comment]
I want to open a pull request that also solves #113, the problem is that there is no way to test the generated code, are you ok with moving certain functions outside of the generated code and instead import them from the package?

This would require `graphql-zeus` to be installed as `dependency` and be tree shakable, I can open a pull for this, do you agree @aexol?

**Comment by aexol** [comment]
Lately I've been playing with JS `toString` function and I think this is the way we should refactor the whole zeus package. It is better than importing from package later IMO.
