### ISSUE TITLE
Use graphql-zeus with apollo

### ISSUE THREAD

**Issue by teevik** [graphql-editor/graphql-zeus#17]
Hey, awesome project! I hope this isn't a stupid question, I couldn't find out anything about it in the docs

Would it be possible to use graphql-zeus together with something like apollo? If so, it'd be super awesome 😀

**Comment by aexol** [comment]
Yes, I want to add support for exporting query only and casting response from apollo to a proper type. First I will export #9 payload type and then I will create Object same as `Api` named `Gql` so you can get pure queries from what you have type in graphql-zeus spec language.

Created issue #18 for that

**Comment by aexol** [comment]
Hi @teevik look into readme, I've just added strings functionality `Zeus` you requested. Also, it is not documented but in javascript, you can cast your response from any other 3rd party tool with `Cast` function
