### ISSUE TITLE
Type mapping

### ISSUE THREAD

**Issue by bkniffler** [graphql-editor/graphql-zeus#170]
Hey, great library! I'm currently trying to make a wrapper for urql and with a simple linq-like syntax. One thing thats still holding me off is.. is there a good way to handle custom types like `uuid` or `timestamp` or `json`? Would love to be able to access `ValueTypes` with these custom mappings somehow, so I won't have unknowns flying around.

Something like `ValueTypes<{json: object, uuid: string}>` or some parameters for the CLI to use a mapping file or whatever solution?

Thanks

**Comment by Vectarian-Jorge** [comment]
Hey @bkniffler, how did you solve it? I'm having a similar issue.

For the return types I see how I can influence the `GraphQLTypes` via the [`ZeusScalars`](https://graphqleditor.com/docs/tools/zeus/graphql/scalars/). But I cannot figure out how to do the same for the `ValueTypes`.

**Comment by bkniffler** [comment]
I've moved on from zeus a while ago @Vectarian-Jorge. Still really thankful for its existence, great library!
