### ISSUE TITLE
Null instead of Undefined

### ISSUE THREAD

**Issue by Maxvien** [graphql-editor/graphql-zeus#171]
This is the `image` field in Shema.
![image](https://user-images.githubusercontent.com/1142799/95305121-c3ab1400-08af-11eb-8329-dce70566cdcb.png)

This is the `image` field which is generated by `graphql-zeus`. It must be `null`, not `undefined`. Do you have an option to config it? 

See also: https://github.com/graphql/graphql-js/issues/1298#issuecomment-377365916

![image](https://user-images.githubusercontent.com/1142799/95305019-a24a2800-08af-11eb-89a9-51536cd61dc6.png)

#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

Now I have to use this function to convert `null` to `undefined`:

```ts
import traverse from "traverse";
import { Chain } from "./hasura.service";

const hasuraService = Chain("https://www.hasura.endpoint");

function nullToUndefined<D extends any>(data: D) {
  return traverse(data).map(function (value) {
    if (value === null) this.update(undefined);
  }) as D;
}

(async () => {
  const data = await hasuraService.query({
    users: [
      {},
      {
        image: true,
      },
    ],
  });

  const { users } = nullToUndefined(data);

  const { image } = users[0]; // const image: string | undefined
})();
```

**Comment by ValentinH** [comment]
I'm facing this issue in v4.0.4:

Here's my type in GraphiQL:
![image](https://user-images.githubusercontent.com/2678610/156797342-60f77ce7-607a-4a67-875a-3f44869e6061.png)

And here's the generated GraphQLTypes:
![image](https://user-images.githubusercontent.com/2678610/156797415-fb3032ac-13ed-41a3-ad5c-dbe43ecd169f.png)

Is this a regression or could I be doing something wrong?

I'm a big fan of this library so I'm available to spend some time to help fixing bugs if needed 👍

**Comment by ValentinH** [comment]
I see this was probably changed in https://github.com/graphql-editor/graphql-zeus/commit/a338a8dd14344c0d39deaba67cf17514231347ad. 
But why ?

**Comment by imbroyury** [comment]
having the same issue as @ValentinH in v4.0.4
@aexol can you help?
