### ISSUE TITLE
Inferred type annotations cause tsc error

### ISSUE THREAD

**Issue by kazazes** [graphql-editor/graphql-zeus#178]
After generating typescript output from a massive schema, tsc fails because of deeply nested type inference.

```ts

src/graphql-zeus.ts:21435:17 - error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
21435 export function Thunder(fn: FetchFunction) {
                      ~~~~~~~

src/graphql-zeus.ts:21475:14 - error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
21475 export const Cast = {
                   ~~~~

src/graphql-zeus.ts:21489:14 - error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
21489 export const Selectors = {
                   ~~~~~~~~~
```

This can be mitigated by explicitly typing the exports:

```ts
interface IChain {
	query: OperationToGraphQL<ValueTypes['query_root'], query_root>
	mutation: OperationToGraphQL<ValueTypes["mutation_root"],mutation_root>
	subscription: OperationToGraphQL<ValueTypes["subscription_root"],subscription_root> 
}
# and then augment the export
export const Chain  = (...options: fetchOptions): IChain => ({...})
```

**Comment by aexol** [comment]
You can try `@beta` version and checkout. However remember TS limits possibilities to 100000 per type so if your schema is too big it wont work

**Comment by kazazes** [comment]
Fair, but it's still a bug and my schema isn't really an edge case. It's small, most of the SDL is from Hasura's obese generated types.

A little explicit typing never hurt anyone.

**Comment by Xetera** [comment]
This doesn't work for me in beta either. My schema is fairly big, is there a way to get around this in a way where I don't have to manually edit the generated typescript files with explicit types after every code generation?

**Comment by tuoxiansp** [comment]
Met the same problem. Use `--node` option might be a workaround here.
