### ISSUE TITLE
Nested type declarations for complex objects.

### ISSUE THREAD

**Issue by RuBAN-GT** [graphql-editor/graphql-zeus#181]
Hi everyone, 

First of all thank you for this amazing library! But I found a strange behaviour related to type definition for an object with nested inputs.

**Example:**
I have a field `assets` which contains another field `metadata` that supports input arguments therefore I should define it using zeus autogenerated client:

```typescript
const response = await client.query()({
  assets: [
    {
      input: {
        where: { ids: ['1234'] },
      },
    },
    {
      assets: {
        id: true,
        metadata: [
          {},
          {
            metadata: {
              field: {
                tagName: true,
                valueType: true,
              },
              '...on TextMetadata': {
                value: true,
              },
            },
          },
        ],
      },
    },
  ],
});
```

From output I'll have the next structure:

```json
{
  "data": {
    "assets": {
      "assets": [
        {
          "id": "1234",
          "metadata": {
            "metadata": [
              {
                "field": {
                  "tagName": "ID",
                  "valueType": "NUMBER"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
 
But Typescript type definition for the response is only supporting first-level declaration and an another deep objects with inputs will be defined as query array.
 
![image](https://user-images.githubusercontent.com/4778223/103347613-87e7ab00-4aa8-11eb-9a52-f26394a1382c.png)

I suppose that is a unexpected library behaviour and probably a new bug.

Thank you!

**Comment by aexol** [comment]
Can you check on `@beta` version?

**Comment by RuBAN-GT** [comment]
Hi @aexol,

Now it takes an input as the type declaration:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/4778223/104091232-1cae8d80-528d-11eb-836a-c122a92d6d38.png">
