### ISSUE TITLE
Inferred type is "undefined" instead of "null"

### ISSUE THREAD

**Issue by benny-medflyt** [graphql-editor/graphql-zeus#184]
When trying out this library I noticed that the inferred result type is `... | undefined` while in reality the runtime type is `... | null`

This means that code like the following compiles correctly, but breaks at runtime:

```typescript
if (result.foo !== undefined) {
    for (const f of result.foo) {
        console.log(f);
    }
}
```

with the error: `TypeError: result.foo is not iterable`

What I should be writing is `if (result.foo !== null)` but then I get a TypeScript compiler error.

I can't write `if (result.foo)` because I have strict eslint config that forbids it.

**Comment by benny-medflyt** [comment]
Oops, looks like this is a duplicate of #171

**Comment by aexol** [comment]
Can you try
```
npm i graphql-zeus@beta
```
