### ISSUE TITLE
[v3] Types not exported independently any more

### ISSUE THREAD

**Issue by bkniffler** [graphql-editor/graphql-zeus#189]
Before, it was possible to `export * as zeus from './graphql-zeus'` and have `zeus` contain all enums and types. This allowed to easily use those to type function arguments, something alike `const saveItem = (item: zeus.item_insert_input) => {...}`. Now, we're forced to use the ValueTypes type and use the `ValueTypes['item_insert_input']` square brackets notation.

It allows for less flexibility and feels like a step backward. Bundling multiple exports to a namespace is easy. So, wouldn't it make sense to go back to exporting all types independently, maybe have a `return-types.ts` and `all-types.ts` file and using them in the generated `index.ts` file like `import * as AllTypes from './all-types` and `import * as ReturnTypes from './return-types'`?

This wouldn't break v3 and would allow for anyone to decide how to export types/enums themselves. What do you think?

**Comment by aexol** [comment]
There is some bug in typescript that when exported independently types break the compilation with maximum number of types exceeded, so that's why I changed it back to 2 files

**Comment by aexol** [comment]
If you can debug whats'going on I believe 3.0.0-18 version is able to test that

**Comment by bkniffler** [comment]
I see 18/19 beta generate more files, though its all similar in that enums are separate exports (which makes sense) but ValueTypes is still an object, not sure what I could test (I'd gladly test/deug anything!). Could you specify please?

I'm not aware that typescript has any limit in terms of number of types, and I couldn't find any documentation for that topic. Are you talking about `tsc`?

**Comment by aexol** [comment]
Yes. It is about 100k max possible combinations. I saw this discussion on ts GitHub as far I remember. Try with very big schema and ts won't compile

**Comment by GavinRay97** [comment]
I can confirm this, I ran into this same problem with another GraphQL library.

Typescript used to let you do this -- then in 4.0 during beta releases they changed it and put a cap on the type complexity:

At least if this is the same problem: _**"Expression produces a union type too complex to represent"**_
I filed an issue about this a while ago: https://github.com/microsoft/TypeScript/issues/38343

This was one of the TS dev's response:

![image](https://user-images.githubusercontent.com/26604994/113441235-f005a000-93bb-11eb-8556-2c654144b910.png)

**Comment by aexol** [comment]
Thanks for the comment. You are 100% right I am rethinking Zeus right now how to make it simpler and language independent
