### ISSUE TITLE
Mysterious "./const" import

### ISSUE THREAD

**Issue by VanCoding** [graphql-editor/graphql-zeus#191]
I can't import the generated zeus client, because it tries to import a "./const" file, which does not exist.
I'm generating the client using `zeus [URL] [folder]` and zeus 3.0.5.

To me it looks, that even the generated client in the examples is non-functional, as it also does import a non-existent "./const" file:
https://github.com/graphql-editor/graphql-zeus/blob/master/examples/javascript-node/src/zeus/index.js#L3

Is this a bug, or am I missing something?

**Comment by VanCoding** [comment]
**update**
I've now quickly tried to run the example, and indeed it crashes with

```
Error: Cannot find module './const'
```

**Comment by aexol** [comment]
You should try now with 3.0.7

**Comment by aexol** [comment]
If the issue persists you can send me your schema so maybe it is an edge case
