### ISSUE TITLE
Possible to switch HTTP method to GET?

### ISSUE THREAD

**Issue by MatthiasGrandl** [graphql-editor/graphql-zeus#195]
I am using Prismic CMS and for some reason their API uses GET for all graphql requests: [link](https://prismic.io/docs/technologies/intro-to-the-graphql-api#a-graphql-api-that-uses-get).

Is it possible to use this library?

**Comment by aexol** [comment]
Hi @MatthiasGrandl You should use Thunder and reimplement fetch inside zeus

**Comment by MatthiasGrandl** [comment]
@aexol that makes sense, but I guess the `Utils.getFromUrl` still wouldn't work, after checking the code. Anyway that's good enough for me. Thanks!
