### ISSUE TITLE
useTypedLazyQuery Addition to new Apollo hooks please

### ISSUE THREAD

**Issue by Spark3000** [graphql-editor/graphql-zeus#207]
New Apollo hooks are great. Can we also get for lazyQuery something like:

```
export function useTypedLazyQuery<Z>(
  query: Z | ValueTypes['query_root'],
  options?: LazyQueryHookOptions<InputType<GraphQLTypes['query_root'], Z>>,
) {
  return useLazyQuery<InputType<ValueTypes['query_root'], Z>>(gql(Zeus.query(query)), options);
}
```

**Comment by Spark3000** [comment]
I would pull request this but I don't know if it's right and Typescript isn't my forté.

**Comment by aexol** [comment]
Of course I can add it. Is there anything more missing?

**Comment by aexol** [comment]
Done in 3.1.5

**Comment by aexol** [comment]
@Spark3000

**Comment by Spark3000** [comment]
Brilliant thanks! Closing.

**Comment by Spark3000** [comment]
> Of course I can add it. Is there anything more missing?

I think there could be some awesome additions for Apollo such as typesafe `readQuery` but I will have proper look and also ask some people.
