### ISSUE TITLE
Comparison with graphql-typed-client ?

### ISSUE THREAD

**Issue by redbar0n** [graphql-editor/graphql-zeus#209]
Reiterated comment from @benny-medflyt over at: https://github.com/helios1138/graphql-typed-client/issues/40

graphql-typed-client seems like a library that is similar to this one.

What advantages does this library have over graphql-typed-client?

zeus seems to have solved some issues that graphql-typed-client has (above link has the relevant issues, for those interested).

On the other hand, graphql-typed-client seems have "custom scalar type mapping" feature which zeus seems to be lacking (?).

I don't mean any disrespect, I am evaluating libraries trying to decide which to use and wondering what advantages these have relative to each other. Has anyone done a comparison?

**Comment by aexol** [comment]
Propose something for custom scalar type. Right now on backend `resolverFor`, I don't want to force for scalar type mapping as this would fire a scalar resolver function on every request. On the front end, you can pass scalars as variables.

Can you suggest how you would like it to look on the front end client?

**Comment by redbar0n** [comment]
Frankly, I haven't got a good enough grasp of [custom scalar type mapping](https://github.com/helios1138/graphql-typed-client#custom-scalar-type-mapping) to tell. The examples there might give some ideas on how it could look on the client. I'm mostly just looking to understand the similarities and differences between the two libraries.

**Comment by aexol** [comment]
Meh it requires configuration. I would rather do smth like:
```tsx
Gql.query({
    someDateScalar:true
},{
  scalars:{
    Date: (q:unknown) => new Date(String(q))
  }
})
```
