### ISSUE TITLE
Do you support a cache like apollo-client or urql?

### ISSUE THREAD

**Issue by frederikhors** [graphql-editor/graphql-zeus#215]
Do you support a cache like apollo-client or urql?

**Comment by aexol** [comment]
You can generate with `--apollo` flag
https://github.com/graphql-editor/graphql-zeus#usage-with-apollo-graphql

**Comment by aexol** [comment]
`urql` coming soon

**Comment by frederikhors** [comment]
Nope. I'm referring to your client. Does it have a cache like urql and apollo'

**Comment by aexol** [comment]
No I want to provide integrations instead.

**Comment by frederikhors** [comment]
Ok. I don't need integrations because I'm already using urql, apollo and codegen. I would like a new normalized cache code to analyse if better (more performant) than them.
