### ISSUE TITLE
Add urql generation

### ISSUE THREAD

**Issue by aexol** [graphql-editor/graphql-zeus#216]

**Comment by thdxr** [comment]
have you thought about what this would look like? thinking about taking a crack at this - already did it once with GenQL

**Comment by aexol** [comment]
Wait for 5.0. 5.0 main goal is to make everything easier for contributors. Now code generation is a mess , in 5.0 zeus will be developable by every mid/senior dev.

**Comment by aexol** [comment]
supported with typed document node
