### ISSUE TITLE
Generate static unbound client 

### ISSUE THREAD

**Issue by Gozala** [graphql-editor/graphql-zeus#219]
At the moment generated code produces client factory function in form of `Chain` which requires user to create a `client` first before using it, which in turn creates a need for dependency injection in non trivial applications. 

This incidental complexity can be removed by generating top level static query, mutation, subscribtion functions that are just like ones returned by `Chain` except they can take config parameter of type

```ts
interface Config extends RequestInit   {
  url: string | URL
}
```

P.S. I don't mind working on a patch provided I can get support from the team

**Comment by aexol** [comment]
There is Thunder now
