### ISSUE TITLE
`--ts` generates errant import to `const.js` in `index.ts`

### ISSUE THREAD

**Issue by jkhoffman** [graphql-editor/graphql-zeus#227]
Hello!

Running Zeus as follows:
`zeus https://my-app.hasura.app/v1/graphql ./utils/generated --ts --apollo`

Results in this import at the top of `utils/generated/zeus/index.ts`:
```
import { AllTypesProps, ReturnTypes } from './const.js';
```

This should be either:
```
import { AllTypesProps, ReturnTypes } from './const.ts';
```
or just
```
import { AllTypesProps, ReturnTypes } from './const';
```

Zeus version: 3.2.5

**Comment by aexol** [comment]
@Gozala

**Comment by aexol** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html
