### ISSUE TITLE
v2 OK, v3 "The inferred type of this node exceeds the maximum length the compiler will serialize" 

### ISSUE THREAD

**Issue by bkniffler** [graphql-editor/graphql-zeus#229]
Tried to upgrade to v3 again today, but I can't get it to work. v2 works great with my Hasura based GraphQL schema and apollo. As soon as I grab the types from v3 generated code, I'm getting:

`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.ts(7056)`

<img width="616" alt="Bildschirmfoto 2021-11-10 um 09 54 10" src="https://user-images.githubusercontent.com/4349324/141081362-ffb072cf-33d2-4ce7-a660-5a2479f5e10a.png">

The code is pretty much the same to the apollo example in your repository. I'm not sure what the exact differences are besides v3 not exporting single types any more (unfortunately).

Related:
https://github.com/graphql-editor/graphql-zeus/issues/178
https://github.com/graphql-editor/graphql-zeus/issues/189

**Comment by aexol** [comment]
We are handling more cases in v3 so we generate more types.  Can you send me the schema or schemaURL to debug.

**Comment by bkniffler** [comment]
Thanks for checking this. I just sent you a mail @aexol. As @kazazes mentioned in the other issue, a fairly simple Hasura schema is enough to trigger the issue. v2 of zeus has no problems with the more complex schema I sent to you.

**Comment by ilijaNL** [comment]
Confirmed, got the same issue. To reproduce, create a hasura graphql endpoint and add view tables, track them and then generate zeus

**Comment by aexol** [comment]
@bkniffler Can you send `.graphql` file or guide me on how I can transform it without writing a custom tool to transform DocumentNode to `graphql`. Maybe you know a tool to transform it to `graphql`? I've never used this DocumentNode format anywhere else than memory

**Comment by bkniffler** [comment]
Just sent you as .gql!

**Comment by ilijaNL** [comment]
What is the status on this issue?

**Comment by aexol** [comment]
I found a solution! Stay tuned I am implementing it now.

**Comment by aexol** [comment]
@bkniffler 4.0.0 deploying now. I did crucial change to support huge schemas. You will need to change syntax just a little bit. Please refer to readme. Apollo and react query also works with big schemas now.
