### ISSUE TITLE
Named queries and mutation for debug purposes

### ISSUE THREAD

**Issue by acestudiooleg** [graphql-editor/graphql-zeus#238]
![image](https://user-images.githubusercontent.com/3492213/145563784-b460a334-3b78-418f-985a-ea4906c76bb9.png)
Sometimes we are using the same query but for different purposes and for different modules.

I would like to have the ability to add names for query

```gql 
query Teacher(where: { type: 'teacher' }) { profile : { name } }
 
query Student(where: { type: 'student' }) { profile : { name } }
```

**Comment by acestudiooleg** [comment]
Oh, sorry, I found `operationName` key for this purpose. Please add it to documentation

**Comment by aexol** [comment]
Thanks Man!

**Comment by WeslleyNasRocha** [comment]
i made a pr #239 to add this to the apollo plugin
