### ISSUE TITLE
JSONB type support with Hasura 

### ISSUE THREAD

**Issue by seanonthenet** [graphql-editor/graphql-zeus#240]
When using GraphQL Zeus (💜 💜 💜) with Hasura and and a Zeus chain generated client and trying to insert a JSONB type value like so: 

```typescript
await myClient('mutation')({
    insert_mything_one: [{
        object: {
            myJsonb: {
                status_code: 0,
                status_description: 'Transaction Successful',
            }
        },
    },{
        id: true,
    }],
});
```

Doesn't work. `invalid GraphQL query`

So I `JSON.stringify()` it but the value is inserted like this in quotes and with all inner quotes escaped:
```JSON
"{\"status_code\":0,\"status_description\":\"Transaction Successful\"}"
```

This works when retrieving it and `JSON.parse()`ing it but it breaks the Hasura JSONB type support where you can query at path which is extremely powerful. 

Hasura wants if formatted like so:
```JSON
{"status_code":0,"status_description":"Transaction Successful"}
```

Is there a way to make this work?

(love Zeus keep up the amazing work ❤️⚡️)

**Comment by seanonthenet** [comment]
Figured it out. No worries. Passing the value as a variable like so:

```typescript
await myClient('mutation')({
    insert_mything_one: [{
        object: {
            ...otherBits,
            myJsonValue: $`myJsonValue`
        },
    },{
        id: true,
    }],
},{
    variables: {
        myJsonValue: myJsonObject
    }
});
```

Works. Thanks. :)

**Comment by 0x15f** [comment]
> @seanonthenet What is the corresponding approach in later versions like 5.0? In the generated zeus.ts `$` is not exported for me,.

`$` is still exported in v5.3
