### ISSUE TITLE
Typescript error on handleFetchResponse

### ISSUE THREAD

**Issue by pikeas** [graphql-editor/graphql-zeus#242]
```
Type 'Promise<unknown>' is not assignable to type 'Promise<GraphQLResponse>'.
  Type 'unknown' is not assignable to type 'GraphQLResponse'.
```

Additionally, the following Typescript flags cause errors:

- "exactOptionalPropertyTypes": true
- "noUncheckedIndexedAccess": true

**Comment by aexol** [comment]
There are more errors if these flags are present I need more time to repair it
