### ISSUE TITLE
Response object when using __alias is named differently to types

### ISSUE THREAD

**Issue by seanonthenet** [graphql-editor/graphql-zeus#257]
Hey guys, 

Aliasing a property in the query:
![Screenshot 2022-03-07 at 18 48 25](https://user-images.githubusercontent.com/4939629/157079590-413f0c19-a778-440a-9fb5-2a0a21279587.png)

Return object is:
![Screenshot 2022-03-07 at 18 48 37](https://user-images.githubusercontent.com/4939629/157079632-15e69b83-3e51-4cc6-a9ef-256fa8155696.png)

and doesn't match the defined return type. Which does have property: `aliasName` not `name__alias__aliasName`

Previous issue here: https://github.com/graphql-editor/graphql-zeus/issues/168 now closed.

Thanks

**Comment by seanonthenet** [comment]
Here's the actual graphql request value from network:

```
{
  order_source_by_pk(id: "a864b79d-3288-4d93-8015-331b9b78270c") {
    id
    created_at
    updated_at
    name__alias__aliasName: name
    __typename
  }
}
```

**Comment by Shervanator** [comment]
We have just run into the same issue. I haven't looked into it much, but managed to get things working with this hack:

```
const seekForAliases = <T extends Record<any, any> | undefined | any[]>(
  response: T
): T => {
  if (Array.isArray(response) && response) {
    return response.map((element) => seekForAliases(element)) as any
  } else if (typeof response === 'object' && response) {
    const output: any = {}

    const keys = Object.keys(response)
    if (keys.length < 1) {
      return output
    }

    for (const k of keys) {
      const value = response[k]

      if (k.includes('__alias__')) {
        const [operation, alias] = k.split('__alias__')
        output[alias] = {
          [operation]: seekForAliases(value),
        }
      } else {
        output[k] = seekForAliases(value)
      }
    }

    return output
  } else {
    return response
  }
}
```

I then use `seekForAliases` like the following:
```
const { data } = useTypedQuery(...)

const cleanedData = useMemo(() => seekForAliases(data), [data])
```

`cleanedData` then is typed correctly and does not include the `name__alias__aliasName` keys.

Which is based on https://github.com/graphql-editor/graphql-zeus/blob/5851076ecfb066a2bf98207b51e883150528f625/examples/typescript-node/src/zeus/index.ts#L599

However that `seekForAliases` seems to attempt to modify the response object and is not immutable, this for some reason seemed to cause issues and not end up adding the correct keys to the `data` returned by the apollo client...

Hope thats a good start, but does seem to be a bug in the package

**Comment by seanonthenet** [comment]
Thanks. Nice hack for now. Hope we can get a fix in the package.

**Comment by aexol** [comment]
I am making 5.0 with correct aliases

**Comment by seanonthenet** [comment]
Awesome! I'm AMPED for the new version 👊👊
