### ISSUE TITLE
Supporting AppSync

### ISSUE THREAD

**Issue by nikodevv** [graphql-editor/graphql-zeus#258]
Our team is using a modified version of the GQL Zeus client so that we can use it with AppSync. The main changes are supporting AWS Scalars types in schema, and remapping the thunder() return function so that it performs an additional mapping.

We are happy to merge our changes into this repo, but we may need some guidance from the authors on the best way to implement our changes. Is there willingness from the maintainers to support our use case?

**Comment by aexol** [comment]
The best way to create it is in plugins folder. What kind of custom logic do you need to support AppSync? I think stitching AWS GraphQL libraries in plugin phase should do the job. Or do you need smth else @nikodevv ?

**Comment by nikodevv** [comment]
I'll take a look at plugins-- we werent aware of that feature thanks.
