### ISSUE TITLE
Support non-hook Apollo query

### ISSUE THREAD

**Issue by thisismydesign** [graphql-editor/graphql-zeus#259]
First off, thanks for addressing support for apollo and https://github.com/graphql-editor/graphql-zeus/issues/194.

`useTypedQuery` works great but in some cases we can't use hooks (e.g. [Next.js SSR `getServerSideProps`](https://stackoverflow.com/questions/64202834/invalid-hook-call-in-getserversideprops-nextjs/71636434#71636434)). I'm relying on this in [`nestjs-starter`](https://github.com/thisismydesign/nestjs-starter) where I added support for typed `client.query` as explained here: https://medium.com/geekculture/automagically-typed-graphql-queries-and-results-with-apollo-3731bad989aa

Could you include a similar `typedQuery` function in the `--apollo` generator?

**Comment by aexol** [comment]
of course. I am in the process of rewriting zeus a little bit to support new `graphql-js-tree` library, so it may be a little bit delayed, but definitely worth adding!
