### ISSUE TITLE
5.0.0 release notes

### ISSUE THREAD

**Issue by ValentinH** [graphql-editor/graphql-zeus#272]
I see that a new major version was published yesterday  but I couldn't find any release notes. 
What are the main changes please?

**Comment by aexol** [comment]
The main changes are in Zeus structure which allows many devs to contribute. The only breaking change is in aliases and variables. New functionality is directives

**Comment by ValentinH** [comment]
What are the breaking changes on aliases and variables?
It would greatly help people migrating if there was a short explanation about these changes 🙂

**Comment by hinsxd** [comment]
Please add some minimal changelog or release notes to help people use this tool!
I am migrating from v2 and the variables `$` behavior has changed a lot. 
And now the docs only says `From 5.1.3 Zeus apollo should be used with graphql-typed-document-node`. At the same time `--apollo` still works but the docs doesn't mention it anymore, and you now have to pass the variables in `{ apolloOptions: { variables } }`. These undocumented changes cost me over a day to figure out the actual behavior thanks to typescript.

So please, let people know the changes!
