### ISSUE TITLE
Node ES Module Support

### ISSUE THREAD

**Issue by xbaun** [graphql-editor/graphql-zeus#274]
Hi, I created a PR for ES module support in the node env. At the moment the `--es` flag is just adding the `.js` extension to imports and not replacing dynamic `require()` calls with the es6  `import` statement. With this change, zeus can be use in node esm projects.

@aexol Would be great if you can take a look at the PR.

See PR #261

**Comment by aexol** [comment]
Can you make it compatible with 5.0?

**Comment by xbaun** [comment]
I can solve the conflicts.

**Comment by xbaun** [comment]
Resolved with v5
