### ISSUE TITLE
TypedDocumentNode losing result typing when arguments are passed to query

### ISSUE THREAD

**Issue by thdxr** [graphql-editor/graphql-zeus#280]
I'm seeing an issue where when I have the following query, everything works right:
```
ZeusTD({
  myQuery: { id: true, other: true }
})
```

However anything requiring arguments loses the return type
```
ZeusTD({
  myQuery: [ { foo: "arg"}, { id: true, other: true }]
})
```

**Comment by thdxr** [comment]
I poked around and using a similiar type signature to the useTypedQuery from the react-query plugin fixes the issue

**Comment by aexol** [comment]
Can you provide PR
