### ISSUE TITLE
Parameterize a Selector

### ISSUE THREAD

**Issue by fubz** [graphql-editor/graphql-zeus#281]
How would I parameterize a Selector so that I could still infer the type of the response.

Take the documentation example as a starting point: https://zeus.graphqleditor.com/page/selector.html
Note: I have no idea how this schema is structured so use a little imagination.

How would I inject 'myInputVariable' into the Selector and still be able to infer the return type?  If I wrap the selector in a function I am no longer able to infer the return type.

```
import { Selector, InputType, GraphQLTypes } from './zeus';

export const drawCardQuery = Selector("Query"){
  Card: [{id: `${myInputVariable}`}, {
    Attack: true,
    Children: true,
    id: true,
  }],
});

type InferredResponseType = InputType<GraphQLTypes['Query'], typeof drawCardQuery>;
```

**Comment by seanonthenet** [comment]
Nice. I will add this to documentation.

**Comment by vxm5091** [comment]
Hey @aexol -- I'm not seeing `useZeusVariables` exported anywhere. Is this example still applicable?
