### ISSUE TITLE
Issue in the docs markdown directives page

### ISSUE THREAD

**Issue by tintin10q** [graphql-editor/graphql-zeus#285]
https://zeus.graphqleditor.com/page/graphql/directives.html

Here the markdown is wrong 

![image](https://user-images.githubusercontent.com/24190849/166107861-d2fa2647-0fa2-4cea-9471-7a9609d24356.png)

**Comment by joserocha3** [comment]
Created [a PR](https://github.com/graphql-editor/graphql-zeus/pull/287) to fix that.

**Comment by joserocha3** [comment]
> 

PR merged by @aexol, thanks!
