### ISSUE TITLE
__directives not getting removed when sending query causes error with Hasura

### ISSUE THREAD

**Issue by tintin10q** [graphql-editor/graphql-zeus#286]
Hi,

I use [Hasura](https://hasura.io) for GraphQL and I am trying  to use the directives feature but it causes an error with Hasura because the `__directives` field is not removed when sending the query.

## Example

I am sending this query:

```js
const human_id = 'human41';
const include_cookies = true;
const result = await Chain("https://hasura.io/tintin10q/graphql")("query")({
        Human_by_pk: [
          { id: human_id },
          {
            cookies: {
              __directives: `@include(if:${include_cookies})`,
             name
            },
            id: true,
            image: true,
          },
        ],
      });
```

This then gets converted into the following query:

```graphql
query { Human_by_pk(id: "human41") {
     cookies @include(if:false) {
         __directives @include(if:true)
           name
         }
         id
         image
     }
}
```

Sadly Hasura returns this error: 

```js
{"errors":[{"extensions":{"path":"$.selectionSet.Human_by_pk.selectionSet.cookies.selectionSet.__directives","code":"validation-failed"},"message":"field \"__directives\" not found in type: 'Cookies'"}]}
```

### What happened?

So basically Hasura checks the query and then does not recognize the `__directives` field and returns an error. To prevent these errors the `__directives` field should be removed from the objects before sending.

This would also send a little less bits over the wire which I think is a good thing because the `__directives` field is just redundant information. 

The `__directives` field not getting removed means that I can't use this feature. 

## Request

Would it be possible for you to remove the `__directives` field from the query before sending? 
Or alternatively to have some sort of config option somewhere to make this happen?

**Comment by aexol** [comment]
Fixed in 5.0.2
