### ISSUE TITLE
Expected an enum value for type but found a string

### ISSUE THREAD

**Issue by META-DREAMER** [graphql-editor/graphql-zeus#293]
When defining enum variables inline in a graphql query, it gives an error that its expecting an enum type but gets a string. This is because graphql expects inline enums to not be wrapped as strings. However, if its passed as a variable, it works fine (since its serialized as JSON and JSON doesnt have enums)

**Comment by seanonthenet** [comment]
Hey @META-DREAMER can you supply a code example?

**Comment by aexol** [comment]
Yes we need that as enums are tested, so we need your edge case

**Comment by tintin10q** [comment]
Did you import the enums from the generated Zeus files? I did not realize that was needed for a bit.

**Comment by aexol** [comment]
Just import an enum and provide it or cast to enum
