### ISSUE TITLE
Date-like object not auto-stringified in v5

### ISSUE THREAD

**Issue by topocount** [graphql-editor/graphql-zeus#295]
in v4, date objects passed as mutation inputs were parsed to iso time strings automatigically. This felt like good ergonomics, but it no longer happening in v5, which requires dates (and luxon DateTimes) to be stringified before the mutation occurs.

Is this intended behavior?

**Comment by aexol** [comment]
Check `graphql-zeus@5.0.3`
https://zeus.graphqleditor.com/page/graphql/scalars.html
How to provide decoders and encoders. This is still fresh and experimental but works and its type safe and tested :)

**Comment by andropov-sergej** [comment]
https://graphqleditor.com/docs/tools/zeus/graphql/scalars/ 

Your examples still not working with 5.3.2 you have to escape the date properly:

```ts
export const scalars = ZeusScalars({
  Date: {
    decode: (e: unknown) => new Date(e as string),
    encode: (e: unknown) => {
      return JSON.stringify(e);
    },
  },
});
```
