### ISSUE TITLE
getting Error in generated apollo.ts 

### ISSUE THREAD

**Issue by abdeljalil09** [graphql-editor/graphql-zeus#305]
![image](https://user-images.githubusercontent.com/101262837/174444739-704f938b-8f86-4371-90af-166f9fb414be.png)

![image](https://user-images.githubusercontent.com/101262837/174444778-9a3f1b6f-b139-40f7-bc9a-835783339d1a.png)

this is how i removed the error , is this okay?

![image](https://user-images.githubusercontent.com/101262837/174444806-e722e9a8-6483-44b9-9d40-9258f9355d07.png)

**Comment by aexol** [comment]
this is ok. This is fixed in 5.0.7 I think
