### ISSUE TITLE
GraphQLTypes with Scalar

### ISSUE THREAD

**Issue by AsafKaravani** [graphql-editor/graphql-zeus#320]
Trying to use `GraphQLTypes['XXXXX_insert_input']`.

![image](https://user-images.githubusercontent.com/16115480/178133598-8a789ed9-04d9-498c-bb38-0a6fb409f40f.png)
![image](https://user-images.githubusercontent.com/16115480/178133607-3136e670-5838-41c9-ba8b-b6350b7ad877.png)

What I'm doing wrong here?

**Comment by AsafKaravani** [comment]
I have downgraded to version 4.0.4 and it kind of solved the problem.
It now types `birthDate` as `any` 
![image](https://user-images.githubusercontent.com/16115480/178136488-7a73e9f6-9697-492b-9264-f8151c59397e.png)

It means there is a bug with version 5 of zeus?

**Comment by aexol** [comment]
Just use zeus Selectors https://zeus.graphqleditor.com/page/selector.html
GraphQLTypes are for internal use

**Comment by aexol** [comment]
@AsafKaravani

**Comment by AsafKaravani** [comment]
> Just use zeus Selectors https://zeus.graphqleditor.com/page/selector.html GraphQLTypes are for internal use

Cool, Thank you! 
The example on the docs gets the response type:
![image](https://user-images.githubusercontent.com/16115480/178155298-d763da70-ad27-49a5-88d4-96c0779461c9.png)

Anyway to get the  mutation input type?

**Comment by aexol** [comment]
Mutation input type is in `ValueTypes` I believe
