### ISSUE TITLE
Scalars are not decoded in mutation responses

### ISSUE THREAD

**Issue by GauBen** [graphql-editor/graphql-zeus#331]
Hey!

Scalars are not decoded in mutation responses, probably because decoding is hardcoded to only work for queries:

https://github.com/graphql-editor/graphql-zeus/blob/45f451c705d49b12b08273973d6de9be45dc7785/src/TreeToTS/functions/new/decodeScalarsInResponse.ts#L31

**Comment by aexol** [comment]
Ok this is to do ASAP

**Comment by GauBen** [comment]
Thanks!
