### ISSUE TITLE
Considering providing a "light version" with no dependencies besides `graphql`

### ISSUE THREAD

**Issue by schickling** [graphql-editor/graphql-zeus#343]
I'd like to use `graphql-zeus` but in my use case I don't need to make any network calls since I have a `GraphQLSchema` locally available which I'd like to query. In my scenario I'd like to avoid any further dependencies such as fetch polyfills, yargs etc.

**Comment by aexol** [comment]
@JedrekDabrowski please create npm workspace with:
- graphql-zeus package as a CLI
- graphql-zeus-core package for zeus functions

The problem is we don't want to have yargs inside `graphql-zeus-core`

**Comment by aexol** [comment]
done in 5.2.1
`graphql-zeus` is acli
`graphql-zeus-core` is else

**Comment by schickling** [comment]
Thanks a lot! Seems like the `json-schema` dep is new. Any reason this is necessary in the core?

**Comment by aexol** [comment]
It is generating JSON schema. We can create separate package `graphql-zeus-jsonschema`

**Comment by aexol** [comment]
done in `5.2.3`
