### ISSUE TITLE
Execute list of queries

### ISSUE THREAD

**Issue by valentin-panalyt** [graphql-editor/graphql-zeus#347]
How can I execute a dynamical list of queries within one graphql request?

The query would always have the same shape but different values, e.g. `{ foo(param: $param) { field1, field2 }}` and I have a list of them.

The final http request should look something like this:
```
{ 
   foo1: foo(param: 1) { field1, field2 }
   foo2: foo(param: 42) { field1, field2 }
   foo3: foo(param: 55) { field1, field2 }
}
```

And I'd like to get a typesafe result that is a list of the responses for the above query. Is there a way to do this without building the query string and the mapping between query and result by hand?

**Comment by aexol** [comment]
Use aliases. Just remember everything is a separate `__alias`
https://graphqleditor.com/docs/tools/zeus/graphql/aliases/
