### ISSUE TITLE
Bug: implemented Interface not working nor properly typed

### ISSUE THREAD

**Issue by Oyelowo** [graphql-editor/graphql-zeus#351]
# Problem
- When a union of types which implement an interface is returned, it should be possible to get the concrete types' values using `inline fragment` with the `interface` name instead of the `concrete types` themselves. This is very useful when doing error handling and you don't want to specifically have to handle each case or manually update new error types on the client side. e.g https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/

## Example issue:
Below should allow interface `Node` inline framgenet to get the common field - `Id` i.e `...on Node { id  true}`
<img width="287" alt="Screenshot 2022-12-01 at 2 57 10" src="https://user-images.githubusercontent.com/31687368/204940625-8fcf22e2-5d6c-4b03-b6f2-66f5f0c992ed.png">

## Example schema:

```graphql
interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  login: String!
}

type Post implements Node {
  id: ID!
  title: String!
  body: String!
}

union UserOrPost = User | Post

type Query {
  entity(id: ID!): UserOrPost
}
```

**Comment by widiak** [comment]
I agree, I also need this functionality.
And I think it should work also if i not use "...on Node" at all.
Simply, if I query for this fragment: 
```{ 
   entity: [
      { id: "" }, 
      { 
         __typeName: true, 
         id: true
       } 
    ]
  }
  ``` 
the return typescript type should work even without using ```...on Node```. But now it returns ```never```.

**Comment by aexol** [comment]
should work in 5.2.2

**Comment by Oyelowo** [comment]
Hi @aexol, thanks for your hard work on this! I just tried using the API, but it didn't seem to work for me. Could you provide some guidance on how to use it correctly, or let me know if there's something I might be missing? Thanks in advance for your help!

<img width="563" alt="Screenshot 2022-12-13 at 18 40 38" src="https://user-images.githubusercontent.com/31687368/207393846-fe124ac6-7267-4e4b-831a-13d503dc5ec9.png">

**Comment by aexol** [comment]
could you provide me with your Zeus generated files? I can debug

**Comment by aexol** [comment]
I see your output is correct right now.

**Comment by aexol** [comment]
I see now you meant unions sharing an interface

**Comment by aexol** [comment]
I can think about it of course. Meanwhile, it would help if you typed fields for each union member. Now, this feature works only if you return the interface from the field. I can think of applying the exact mechanism to unions.

**Comment by Oyelowo** [comment]
that's right, when you return an interface, it works as expected. However, when some or all members of a union implement the same interface, it should be possible to use the interface and get a union of the concrete types with only the fields defined in the interface and the __typename of the respective concrete types 🤔
