### ISSUE TITLE
Support injecting a custom `fetch` fn into Chain()

### ISSUE THREAD

**Issue by rjmackay** [graphql-editor/graphql-zeus#366]
If the generated apiFetch function supported passing fetch as an option it would be much easier to customise what fetch library is being used without re-implementing apiFetch

**Comment by rjmackay** [comment]
I realize this was raised in #143, but having to reimplement all of apiFetch with Thunder is a lot more work than just overriding fetch() itself.

**Comment by aexol** [comment]
Ok we can reexport and provide easier way for doing this

**Comment by jasonkuhrt** [comment]
I want this feature so that we can query against an in-memory graph. Is there a better way?

**Comment by aexol** [comment]
It is so hard to write simple fetching function or copy paste from Zeus and modify ;)?

**Comment by aexol** [comment]
Just use Thunder

**Comment by jasonkuhrt** [comment]
@aexol figured that out yep, thanks.
