### ISSUE TITLE
Inferred type exceeds the maximum length the compiler will serialize

### ISSUE THREAD

**Issue by donferi** [graphql-editor/graphql-zeus#382]
Hello,

I'm trying to create a couple of wrapper functions where I accept a generic of `TData extends ValueTypes['Query']` but when I use this with a `declaration: true` in tsconfig I get TS error. 

> The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

I'm working on a library so I can't disable `declaration: true`. I created a small repro that reproduces this here:
https://github.com/donferi/zeus-ts/blob/690211ccfad13e492b0d0ee3186ace1841d476de/src/example.ts#L10:L13

In that same repo I have an example with `genql` and it seems to be working fine, added it just in case it sparks some ideas of how this could potentially work.

**Comment by rtmruczek** [comment]
I had the same issue. I ended up swapping out zeus for genql and had no issues

**Comment by aexol** [comment]
This is not zeus issue, but TS limitation - it happens when you reexport packages inside custom package. This however has been fixed in the latest version, by allowing to set up custom scalars one level up inside Thunder function
