### ISSUE TITLE
Type safety in Selectors and chain('query')

### ISSUE THREAD

**Issue by klonwar** [graphql-editor/graphql-zeus#393]
Hi, I faced an issue when using Selectors. Real life use case: our API schema changed. After updating the zeus client I saw all the fields that changed their name or disappeared, but only in chain('query') without selectors.

Take a look on the example:

```ts
const CategoriesSelector = Selector('ArticleCategoryEntityResponse')({
  missing: true, // No TS error
})

chain('query')({
  articleCategories: [{ locale: language, sort: ['label'] }, CategoriesSelector], // No TS error
})
```

The error is not shown in either query or selector. If I try to query the "missing" field there is no error too, and it's type is `unknown`.

![image](https://github.com/graphql-editor/graphql-zeus/assets/12374932/065c8bf6-ff34-4e33-a210-f7105126a13d)

However if I copy exactly the same object but without selector it shows an error:

```ts
chain('query')({
  articleCategories: [{ locale: language, sort: ['label'] }, {
    missing: true // <-- TS2353: Object literal may only specify known properties, and missing does not exist in type
  }],
})
```

In the meanwhile autocomplete works perfectly either in selector and query, so TS knows what fields are allowed here.

So, is there any way to have same type safety as in raw chain('query') when using such selectors?
I want them to be reusable and have the same checks for not allowed fields as in query. Making `Selector('Query')` is not an option for me, since I will not be able to reuse it in other selectors and queries.

**Comment by RuBAN-GT** [comment]
Hey @klonwar,
What is the `CategoriesSelector` forecasted type?

**Comment by klonwar** [comment]
@RuBAN-GT In our case we have `ArticleCategoryEntityResponse` type:

```ts
// graphql-zeus index.ts file:
...
["ArticleCategoryEntityResponse"]: AliasType<{
	data?:ValueTypes["ArticleCategoryEntity"],
		__typename?: boolean | `@${string}`
}>;
...
```

So, the only allowed field here is "data" field. I added apparently nonexistent "missing" field to show example of situation when type checks works differently in `Query` and `Selector`

**Comment by aexol** [comment]
Done in 5.4.0, the only thing left is arguments
