### ISSUE TITLE
Abstract fetch part and make it replaceable

### ISSUE THREAD

**Issue by aexol** [graphql-editor/graphql-zeus#49]

**Comment by regevbr** [comment]
Indeed will be a great idea!

**Comment by cjanietz** [comment]
+1 This would really help, currently the global fetch is not really nice.
Would be nice if it was just part of the Chain argument for fetchOptions
@aexol

**Comment by aexol** [comment]
Starting now then!

**Comment by aexol** [comment]
done

**Comment by aexol** [comment]
with e2e tests ofc and integration tests
