### ISSUE TITLE
Is there any plans to improve selection typing?

### ISSUE THREAD

**Issue by user471** [graphql-editor/graphql-zeus#73]
Even if I choose some fields, I would still get full object type.
```
   export type Foo = {
	x: number,
	y: number
    }

    const foo = await Api("localhost").Query.foo([{}, {x: true}])
    const y = foo.y

```
I am not sure what is the best way to fix it. Maybe instead of object it could use function.
```
 await Api("localhost").Query.foo([{}, foo => foo.x])
```
You could pass proxy object to this function to understand that `x` field was read.

**Comment by aexol** [comment]
This is intended. GraphQL Server returns data in this format. So you should get `foo` object only and zeus only changes `response => response.foo`

**Comment by user471** [comment]
@aexol Sorry, I don't get what do you mean.
When I use 
```
 {x: true}
```
I only get `x` field, but typing allow me to use other fields like `y`.

**Comment by aexol** [comment]
Yeah I have plans for that, but it is much more complicated. Right now every type is optional as in GraphQL you can select any property. If you want to store data fro zeus you can use `PlainObject<Foo>`
This is not yet documented but this way you can store results in your data store without recasting them to another type. In future I will add these intersection types

**Comment by dandrei** [comment]
I played a bit with Mapped Types, and here's how this feature can be implemented:

Given an `OriginalType` like this: (coming from GraphQL):
```
type OriginalType = {
    field1: string,
    field2: number
    field3: {
        field4: string
        field5: string
    }
};
```

And given an extraction pattern like this:
```
const pattern = {
    field1: true,
    field3: {
        field4: true
    }
};
type DefinitionType = typeof pattern;
```

The following `MapType` type will extract the deep structure of the original type, where the fields intersect with the `DefinitionType`:
```
type Anify<T> = { [P in keyof T]: any };

type MapType<SRC extends Anify<DST>, DST> = {
    [Key in keyof DST]: DST[Key] extends boolean
        ? SRC[Key]
        : MapType<SRC[Key], DST[Key]>
};
```

Example:
```
type DestinationType = MapType<OriginalType, DefinitionType>;

// no errors at this point, this is what the GraphQL query should return
const dest: DestinationType = {
    field1: "123",
    field3: {
        field4: "as",
    }
};
```

**Comment by aexol** [comment]
Thanks Andrei @dandrei ! I will play with it today. Thank you!

**Comment by aexol** [comment]
@dandrei It works but I think it is impossible to infer it in function while having autocomplete at the same time :|

**Comment by aexol** [comment]
```ts


type MMS = {
  name: string;
  age: number;
  id: string;
  www: {
    m: string;
  };
};
type Statess<T> = {
  [P in keyof T]?: true;
};
type PropertyNames<T, Z> = {
  [K in keyof T]: K extends keyof Z ? K : never;
}[keyof T];

type Picker<Z> = <T>(a: T) => Pick<Z, PropertyNames<T, Z>>;
const bb: Picker<MMS> = param => {
  return {} as any;
};
const aa = bb({
  name: true,
});
It works but no autocomplete on bb is present. Help me @dandrei . Don't put me in the rabbit hole.
```

**Comment by aexol** [comment]
did it and it works!! Expect update this week

**Comment by dandrei** [comment]
Cool, how did you do it? I've been playing around with some solutions but I didn't find one that both:
- Complains when the input pattern has extra fields (e.g. requesting a field that isn't present)
- Returns the specified subtype.

**Comment by aexol** [comment]
MappedType + Union. I am changing everything in zeus now. Thanks for the first suggestion

**Comment by dandrei** [comment]
Cool, can't wait. How are you using unions? Here's something I'm doing (manually so far) in my GraphQL code:

Given a GraphQL full type definition:

    {
      field1: string
      field2: string
      field3: {
        field31: number
        field32: string
      }
    }

When I'd query:

    {
      field1
      field3 {
        field31
        field32
      }
    }

I'd manually produce:

    type ResultingType = WithField1 & WithField3

Where:

    type WithField1 = {
      field1: string
    }

    type WithField3 = {
      field31: number
      field32: string
    }

Is your approach similar?
