### ISSUE TITLE
rename Zeus's internal types to avoid conflicts

### ISSUE THREAD

**Issue by dielduarte** [graphql-editor/graphql-zeus#82]
After generating Zeus's file we've had a problem `duplicate identifier`  which breaks Ts compilation.

In my case, the problem is that our API has a `State` type, and also Zeus has a `State` generic type

**Comment by dielduarte** [comment]
hey! @aexol any news? do you need help with something?

**Comment by aexol** [comment]
Sorry I was busy with new GraphQL editor release. I think I can try to do it next week. However if you can contribute that would be very helpful. DM me on slack please
