### ISSUE TITLE
send two or three params with Authorization header

### ISSUE THREAD

**Issue by fandu139** [graphql-editor/graphql-zeus#84]
hai guys, how to send two or three params with Authorization header, for example on zeus using send one params `$ zeus https://faker.graphqleditor.com/aexol/olympus/graphql ./generated --header=Authorization:dsadasdASsad` and i'm using three params, example i using three header is x-access-token, x-grant-code and logic, do i have use it like this `zeus https://xxxxx.com/graphql ./src/generated --header=x-grant-code:2dd5a081fabd9a6e3728;x-access-token:mOZb7091e3fc3f9;logic:mobile`, how to solve my problem?

**Comment by aexol** [comment]
Great idea I will add the possibility of adding more headers

**Comment by fandu139** [comment]
thanks mr. aexol
