### ISSUE TITLE
Add eslint ignore to the top of generated file

### ISSUE THREAD

**Issue by aexol** [graphql-editor/graphql-zeus#87]

**Comment by gfranco93** [comment]
Can you elaborate further?

**Comment by aexol** [comment]
one line like tslint ignore on top of generated file

**Comment by aexol** [comment]
@gfranco93 TreeToTS/index.ts please add both for JS and TS

**Comment by akhil-ghatiki** [comment]
@aexol I have raised a PR for this yesterday. Can you look into it once ?
