### ISSUE TITLE
Support Interface Types

### ISSUE THREAD

**Issue by cjanietz** [graphql-editor/graphql-zeus#93]
First off, really nice work on this lib.
Unfortunately currently there is no support for choosing properties on interface types and thereby receiving these as a result. It should be similar to the union type implementation
Any chance this will be added soon?

**Comment by aexol** [comment]
Hi! Thanks for the issue. Interfaces are supported in zeus. What kind of support do you lack? I can implement ASAP

**Comment by aexol** [comment]
If you mean mapped types then of course this is possible but it is very complicated tho. I tried adding that but lost autocomplete with it somehow

**Comment by aexol** [comment]
did it and it works!! Expect update this week

**Comment by cjanietz** [comment]
> If you mean mapped types then of course this is possible but it is very complicated tho. I tried adding that but lost autocomplete with it somehow

Basically you receive a type User but you want to select properties on the specialization such as "... on Person" with "type Person implements User". If this what you mean by mapped types, thats pretty much it. Its nice if you already got it running, looking forward to it.

**Comment by cjanietz** [comment]
Hello @aexol , I checked version 2.0 but it is not in there or not working as I would have expected. Maybe I provide a more clear example:
`
interface User {
  userId: String
}

type Person implements User {
  firstname: String
}

type Query {
  user(id: ID!): User
}
`

I would expect to query this, this way:
`
{
  user: {
    '... on Person': {
      firstname: true
    }
  }
}
`

Do you understand what I mean?

**Comment by aexol** [comment]
Yes I will provide in next fix !

**Comment by aexol** [comment]
@cjanietz done

**Comment by cjanietz** [comment]
@aexol this is still not working for me
I tried with this simple example
```
interface User {
    id: String!
}

type Person implements User {
    name: String!
}

type Query {
    user: User!
}
```
And I can unfortunately not query "... on Person" when selecting user on the query :(

**Comment by aexol** [comment]
```
"User" expects field "id" but "Person" does not provide it.
``` ;)

**Comment by aexol** [comment]
You have an error in your schema

**Comment by aexol** [comment]
![Screen Shot 2019-11-13 at 10 13 25](https://user-images.githubusercontent.com/779748/68749313-4d018a00-05fe-11ea-82a2-0d4bff4c7ee3.png)
![Screen Shot 2019-11-13 at 10 13 18](https://user-images.githubusercontent.com/779748/68749314-4d9a2080-05fe-11ea-83ab-306397a48661.png)

**Comment by aexol** [comment]
@cjanietz

**Comment by cjanietz** [comment]
Okay I am sorry @aexol it works perfectly, thanks
There was a mess up with yarn not updating the package
