### ISSUE TITLE
add headers to Chain and Selectors

### ISSUE THREAD

**Issue by MJGTwo** [graphql-editor/graphql-zeus#94]
First, I really like the idea behind this library; not dealing with string literals is great.

I am curious if you will add support to Chain and Selector to add headers to the query. 

For my project, I have my login logic at `/auth/` which returns a Bearer token to use the GraphQL logic at `/graphql/`. I have everything behind GraphQL Shield which grabs the `Authorization` header from the request which contains the Bearer token. There doesn't appear to be a way to add a header with the token, so I think it would be a good addition to your project.

**Comment by aexol** [comment]
Hi Michael,
there is a way to add headers already and I think I should document it :
```ts
const chain = Chain('https://faker.graphqleditor.com/aexol/olympus/graphql',{
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer: 4321m4i3joi4j1oi'
      },
});
```
Basicly Chain inherits second argument from fetch options. You're welcome, have a nice day!

```

**Comment by aexol** [comment]
Selector is only for payload generation so no headers there.

**Comment by MJGTwo** [comment]
@aexol Thanks for explaining that!

**Comment by mash-graz** [comment]
> there is a way to add headers already and I think I should document it :
> 
> ```ts
> const chain = Chain('https://faker.graphqleditor.com/aexol/olympus/graphql',{
>       headers: {
>         'Content-Type': 'application/json',
>         'Authorization': 'Bearer: 4321m4i3joi4j1oi'
>       },
> });
> ```

@aexol 
yes -- it would be nice, if this hint would find it's way into the documentation! ;)
i was  also looking for an answer to this question and finally found it here.

**Comment by tintin10q** [comment]
I couldn't find this tip in the docs yet but I just started using this today. 

Is it also possible to set headers at runtime? Or do I just have to call the Chain function again to do that?
